INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (1,'AF','AFG','Afghanistan'),
	 (2,'AX','ALA','Aland Islands'),
	 (3,'AL','ALB','Albania'),
	 (4,'DZ','DZA','Algeria'),
	 (5,'AS','ASM','American Samoa'),
	 (6,'AD','AND','Andorra'),
	 (7,'AO','AGO','Angola'),
	 (8,'AI','AIA','Anguilla'),
	 (9,'AQ','ATA','Antarctica'),
	 (10,'AG','ATG','Antigua And Barbuda');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (11,'AR','ARG','Argentina'),
	 (12,'AM','ARM','Armenia'),
	 (13,'AW','ABW','Aruba'),
	 (14,'AU','AUS','Australia'),
	 (15,'AT','AUT','Austria'),
	 (16,'AZ','AZE','Azerbaijan'),
	 (18,'BH','BHR','Bahrain'),
	 (19,'BD','BGD','Bangladesh'),
	 (20,'BB','BRB','Barbados'),
	 (21,'BY','BLR','Belarus');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (22,'BE','BEL','Belgium'),
	 (23,'BZ','BLZ','Belize'),
	 (24,'BJ','BEN','Benin'),
	 (25,'BM','BMU','Bermuda'),
	 (26,'BT','BTN','Bhutan'),
	 (27,'BO','BOL','Bolivia'),
	 (155,'BQ','BES','Bonaire, Sint Eustatius and Saba'),
	 (28,'BA','BIH','Bosnia and Herzegovina'),
	 (29,'BW','BWA','Botswana'),
	 (30,'BV','BVT','Bouvet Island');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (31,'BR','BRA','Brazil'),
	 (32,'IO','IOT','British Indian Ocean Territory'),
	 (33,'BN','BRN','Brunei'),
	 (34,'BG','BGR','Bulgaria'),
	 (35,'BF','BFA','Burkina Faso'),
	 (36,'BI','BDI','Burundi'),
	 (37,'KH','KHM','Cambodia'),
	 (38,'CM','CMR','Cameroon'),
	 (39,'CA','CAN','Canada'),
	 (40,'CV','CPV','Cape Verde');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (41,'KY','CYM','Cayman Islands'),
	 (42,'CF','CAF','Central African Republic'),
	 (43,'TD','TCD','Chad'),
	 (44,'CL','CHL','Chile'),
	 (45,'CN','CHN','China'),
	 (46,'CX','CXR','Christmas Island'),
	 (47,'CC','CCK','Cocos (Keeling) Islands'),
	 (48,'CO','COL','Colombia'),
	 (49,'KM','COM','Comoros'),
	 (50,'CG','COG','Congo');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (52,'CK','COK','Cook Islands'),
	 (53,'CR','CRI','Costa Rica'),
	 (54,'CI','CIV','Cote D''Ivoire (Ivory Coast)'),
	 (55,'HR','HRV','Croatia'),
	 (56,'CU','CUB','Cuba'),
	 (249,'CW','CUW','Curaçao'),
	 (57,'CY','CYP','Cyprus'),
	 (58,'CZ','CZE','Czech Republic'),
	 (51,'CD','COD','Democratic Republic of the Congo'),
	 (59,'DK','DNK','Denmark');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (60,'DJ','DJI','Djibouti'),
	 (61,'DM','DMA','Dominica'),
	 (62,'DO','DOM','Dominican Republic'),
	 (63,'TL','TLS','East Timor'),
	 (64,'EC','ECU','Ecuador'),
	 (65,'EG','EGY','Egypt'),
	 (66,'SV','SLV','El Salvador'),
	 (67,'GQ','GNQ','Equatorial Guinea'),
	 (68,'ER','ERI','Eritrea'),
	 (69,'EE','EST','Estonia');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (70,'ET','ETH','Ethiopia'),
	 (71,'FK','FLK','Falkland Islands'),
	 (72,'FO','FRO','Faroe Islands'),
	 (73,'FJ','FJI','Fiji Islands'),
	 (74,'FI','FIN','Finland'),
	 (75,'FR','FRA','France'),
	 (76,'GF','GUF','French Guiana'),
	 (77,'PF','PYF','French Polynesia'),
	 (78,'TF','ATF','French Southern Territories'),
	 (79,'GA','GAB','Gabon');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (80,'GM','GMB','Gambia The'),
	 (81,'GE','GEO','Georgia'),
	 (82,'DE','DEU','Germany'),
	 (83,'GH','GHA','Ghana'),
	 (84,'GI','GIB','Gibraltar'),
	 (85,'GR','GRC','Greece'),
	 (86,'GL','GRL','Greenland'),
	 (87,'GD','GRD','Grenada'),
	 (88,'GP','GLP','Guadeloupe'),
	 (89,'GU','GUM','Guam');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (90,'GT','GTM','Guatemala'),
	 (91,'GG','GGY','Guernsey and Alderney'),
	 (92,'GN','GIN','Guinea'),
	 (93,'GW','GNB','Guinea-Bissau'),
	 (94,'GY','GUY','Guyana'),
	 (95,'HT','HTI','Haiti'),
	 (96,'HM','HMD','Heard Island and McDonald Islands'),
	 (97,'HN','HND','Honduras'),
	 (98,'HK','HKG','Hong Kong S.A.R.'),
	 (99,'HU','HUN','Hungary');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (100,'IS','ISL','Iceland'),
	 (101,'IN','IND','India'),
	 (102,'ID','IDN','Indonesia'),
	 (103,'IR','IRN','Iran'),
	 (104,'IQ','IRQ','Iraq'),
	 (105,'IE','IRL','Ireland'),
	 (106,'IL','ISR','Israel'),
	 (107,'IT','ITA','Italy'),
	 (108,'JM','JAM','Jamaica'),
	 (109,'JP','JPN','Japan');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (110,'JE','JEY','Jersey'),
	 (111,'JO','JOR','Jordan'),
	 (112,'KZ','KAZ','Kazakhstan'),
	 (113,'KE','KEN','Kenya'),
	 (114,'KI','KIR','Kiribati'),
	 (248,'XK','XKX','Kosovo'),
	 (117,'KW','KWT','Kuwait'),
	 (118,'KG','KGZ','Kyrgyzstan'),
	 (119,'LA','LAO','Laos'),
	 (120,'LV','LVA','Latvia');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (121,'LB','LBN','Lebanon'),
	 (122,'LS','LSO','Lesotho'),
	 (123,'LR','LBR','Liberia'),
	 (124,'LY','LBY','Libya'),
	 (125,'LI','LIE','Liechtenstein'),
	 (126,'LT','LTU','Lithuania'),
	 (127,'LU','LUX','Luxembourg'),
	 (128,'MO','MAC','Macau S.A.R.'),
	 (129,'MK','MKD','Macedonia'),
	 (130,'MG','MDG','Madagascar');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (131,'MW','MWI','Malawi'),
	 (132,'MY','MYS','Malaysia'),
	 (133,'MV','MDV','Maldives'),
	 (134,'ML','MLI','Mali'),
	 (135,'MT','MLT','Malta'),
	 (136,'IM','IMN','Man (Isle of)'),
	 (137,'MH','MHL','Marshall Islands'),
	 (138,'MQ','MTQ','Martinique'),
	 (139,'MR','MRT','Mauritania'),
	 (140,'MU','MUS','Mauritius');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (141,'YT','MYT','Mayotte'),
	 (142,'MX','MEX','Mexico'),
	 (143,'FM','FSM','Micronesia'),
	 (144,'MD','MDA','Moldova'),
	 (145,'MC','MCO','Monaco'),
	 (146,'MN','MNG','Mongolia'),
	 (147,'ME','MNE','Montenegro'),
	 (148,'MS','MSR','Montserrat'),
	 (149,'MA','MAR','Morocco'),
	 (150,'MZ','MOZ','Mozambique');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (151,'MM','MMR','Myanmar'),
	 (152,'NA','NAM','Namibia'),
	 (153,'NR','NRU','Nauru'),
	 (154,'NP','NPL','Nepal'),
	 (156,'NL','NLD','Netherlands'),
	 (157,'NC','NCL','New Caledonia'),
	 (158,'NZ','NZL','New Zealand'),
	 (159,'NI','NIC','Nicaragua'),
	 (160,'NE','NER','Niger'),
	 (161,'NG','NGA','Nigeria');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (162,'NU','NIU','Niue'),
	 (163,'NF','NFK','Norfolk Island'),
	 (115,'KP','PRK','North Korea'),
	 (164,'MP','MNP','Northern Mariana Islands'),
	 (165,'NO','NOR','Norway'),
	 (166,'OM','OMN','Oman'),
	 (167,'PK','PAK','Pakistan'),
	 (168,'PW','PLW','Palau'),
	 (169,'PS','PSE','Palestinian Territory Occupied'),
	 (170,'PA','PAN','Panama');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (171,'PG','PNG','Papua new Guinea'),
	 (172,'PY','PRY','Paraguay'),
	 (173,'PE','PER','Peru'),
	 (174,'PH','PHL','Philippines'),
	 (175,'PN','PCN','Pitcairn Island'),
	 (176,'PL','POL','Poland'),
	 (177,'PT','PRT','Portugal'),
	 (178,'PR','PRI','Puerto Rico'),
	 (179,'QA','QAT','Qatar'),
	 (180,'RE','REU','Reunion');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (181,'RO','ROU','Romania'),
	 (182,'RU','RUS','Russia'),
	 (183,'RW','RWA','Rwanda'),
	 (184,'SH','SHN','Saint Helena'),
	 (185,'KN','KNA','Saint Kitts And Nevis'),
	 (186,'LC','LCA','Saint Lucia'),
	 (187,'PM','SPM','Saint Pierre and Miquelon'),
	 (188,'VC','VCT','Saint Vincent And The Grenadines'),
	 (189,'BL','BLM','Saint-Barthelemy'),
	 (190,'MF','MAF','Saint-Martin (French part)');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (191,'WS','WSM','Samoa'),
	 (192,'SM','SMR','San Marino'),
	 (193,'ST','STP','Sao Tome and Principe'),
	 (194,'SA','SAU','Saudi Arabia'),
	 (195,'SN','SEN','Senegal'),
	 (196,'RS','SRB','Serbia'),
	 (197,'SC','SYC','Seychelles'),
	 (198,'SL','SLE','Sierra Leone'),
	 (199,'SG','SGP','Singapore'),
	 (250,'SX','SXM','Sint Maarten (Dutch part)');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (200,'SK','SVK','Slovakia'),
	 (201,'SI','SVN','Slovenia'),
	 (202,'SB','SLB','Solomon Islands'),
	 (203,'SO','SOM','Somalia'),
	 (204,'ZA','ZAF','South Africa'),
	 (205,'GS','SGS','South Georgia'),
	 (116,'KR','KOR','South Korea'),
	 (206,'SS','SSD','South Sudan'),
	 (207,'ES','ESP','Spain'),
	 (208,'LK','LKA','Sri Lanka');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (209,'SD','SDN','Sudan'),
	 (210,'SR','SUR','Suriname'),
	 (211,'SJ','SJM','Svalbard And Jan Mayen Islands'),
	 (212,'SZ','SWZ','Swaziland'),
	 (213,'SE','SWE','Sweden'),
	 (214,'CH','CHE','Switzerland'),
	 (215,'SY','SYR','Syria'),
	 (216,'TW','TWN','Taiwan'),
	 (217,'TJ','TJK','Tajikistan'),
	 (218,'TZ','TZA','Tanzania');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (219,'TH','THA','Thailand'),
	 (17,'BS','BHS','The Bahamas'),
	 (220,'TG','TGO','Togo'),
	 (221,'TK','TKL','Tokelau'),
	 (222,'TO','TON','Tonga'),
	 (223,'TT','TTO','Trinidad And Tobago'),
	 (224,'TN','TUN','Tunisia'),
	 (225,'TR','TUR','Turkey'),
	 (226,'TM','TKM','Turkmenistan'),
	 (227,'TC','TCA','Turks And Caicos Islands');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (228,'TV','TUV','Tuvalu'),
	 (229,'UG','UGA','Uganda'),
	 (230,'UA','UKR','Ukraine'),
	 (231,'AE','ARE','United Arab Emirates'),
	 (232,'GB','GBR','United Kingdom'),
	 (233,'US','USA','United States'),
	 (234,'UM','UMI','United States Minor Outlying Islands'),
	 (235,'UY','URY','Uruguay'),
	 (236,'UZ','UZB','Uzbekistan'),
	 (237,'VU','VUT','Vanuatu');
INSERT INTO public.country (country_id,country_iso2,country_iso3,"name") VALUES
	 (238,'VA','VAT','Vatican City State (Holy See)'),
	 (239,'VE','VEN','Venezuela'),
	 (240,'VN','VNM','Vietnam'),
	 (241,'VG','VGB','Virgin Islands (British)'),
	 (242,'VI','VIR','Virgin Islands (US)'),
	 (243,'WF','WLF','Wallis And Futuna Islands'),
	 (244,'EH','ESH','Western Sahara'),
	 (245,'YE','YEM','Yemen'),
	 (246,'ZM','ZMB','Zambia'),
	 (247,'ZW','ZWE','Zimbabwe');
